# .github/workflows/elixir-ci.yml
name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: main_app_test1
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MIX_ENV: test
      DATABASE_URL: ecto://postgres:postgres@localhost/multitenant_test
      MIX_TEST_PARTITION: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore mix deps & build cache
        uses: actions/cache@v4
        id: cache
        env:
          OTP_VERSION: ${{ steps['setup-elixir'].outputs.otp-version }}
          ELIXIR_VERSION: ${{ steps['setup-elixir'].outputs.elixir-version }}
          MIX_LOCK_HASH: ${{ hashFiles('**/mix.lock') }}
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ env.MIX_ENV }}-mix-${{ env.MIX_LOCK_HASH }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile project
        run: mix compile --force

#      - name: Check formatting
#        run: mix format --check-formatted

#      - name: Run Credo (lint)
#        run: mix credo --strict

      - name: Run tests
        run: mix test
