# .github/workflows/elixir-ci.yml
name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Restore mix deps & build cache
        uses: actions/cache@v4
        id: cache
        env:
          OTP_VERSION: ${{ steps['setup-elixir'].outputs.otp-version }}
          ELIXIR_VERSION: ${{ steps['setup-elixir'].outputs.elixir-version }}
          MIX_LOCK_HASH: ${{ hashFiles('**/mix.lock') }}
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ env.MIX_ENV }}-mix-${{ env.MIX_LOCK_HASH }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile project
        run: mix compile --force

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo (lint)
        run: mix credo --strict

      - name: Run tests
        run: mix test
